### PR TITLE
Review for Newsweek clone project

### PR DESCRIPTION
**Pull request by asiimwedismas**
Hello, Newsweek project created using mostly bootstrap. I did, however, include a few of my own classes that bootstrap does not provide. Please have a look and let me know if anything needs improvement

### CODE REVIEW

**Comment by trekab** [comment]
# Changes Required!
Hello @asiimwedismas, impressive job! :clap: There are a few things to look at to finalize with this project though.

## Required changes:
- [x] On small screen sizes, the main content should have "TOP STORY" as the leading section. ([original site](https://www.newsweek.com/)) This will make [your clone](https://rawcdn.githack.com/asiimwedismas/Newsweek-clone/f25a12a0e67f8f256ad9865d1017f2dd45d01271/index.html) look more like the [original site](https://www.newsweek.com/).
- [x] The navigation links and footer links look different from the [original site](https://www.newsweek.com/) on hovering. It would make [your clone](https://rawcdn.githack.com/asiimwedismas/Newsweek-clone/f25a12a0e67f8f256ad9865d1017f2dd45d01271/index.html) look more like the [original site](https://www.newsweek.com/) if you styled them appropriately.

## Optional changes:
- [x] There appears to be too much space between the main navigation and the Newsweek logo section. Compare with [original site](https://www.newsweek.com/).

Great job implementing most of the required changes so far.
__Kindly work the required changes and submit another code review request__
_Feel free to reach me on slack for any inquiries about this review_ :wink: 
__Treasure Kabareebe__

**Comment by asiimwedismas** [comment]
> # Changes Required!
> Hello @asiimwedismas, impressive job! 👏 There are a few things to look at to finalize with this project though.
> 
> ## Required changes:
> * [x]  On small screen sizes, the main content should have "TOP STORY" as the leading section. ([original site](https://www.newsweek.com/)) This will make [your clone](https://rawcdn.githack.com/asiimwedismas/Newsweek-clone/f25a12a0e67f8f256ad9865d1017f2dd45d01271/index.html) look more like the [original site](https://www.newsweek.com/).
> * [x]  The navigation links and footer links look different from the [original site](https://www.newsweek.com/) on hovering. It would make [your clone](https://rawcdn.githack.com/asiimwedismas/Newsweek-clone/f25a12a0e67f8f256ad9865d1017f2dd45d01271/index.html) look more like the [original site](https://www.newsweek.com/) if you styled them appropriately.
> 
> ## Optional changes:
> * [x]  There appears to be too much space between the main navigation and the Newsweek logo section. Compare with [original site](https://www.newsweek.com/).
> 
> Great job implementing most of the required changes so far.
> **Kindly work the required changes and submit another code review request**
> _Feel free to reach me on slack for any inquiries about this review_ 😉
> **Treasure Kabareebe**

All Issues raised have been fixed, Thanks

**Comment by santiago-dev96** [comment]
## Pull Request under review by @santiago-rodrig (TSE)

**Review by santiago-dev96 — APPROVED** [review]
# Project approved! :100:

Your project meets all the requirements, you're free to continue. Have a nice day!

**Pull request merged**
